version: '3.8'
services:
  fastapi:
    build: .
    container_name: fastapi_ratelimit_app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    container_name: redis_ratelimit
    ports:
      - "6379:6379" 